name: Test @iwsio/json-csv-core

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x, 20.x, 22.x, 24.x]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js 24 (for build)
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'
    - run: npm ci -w packages/json-csv-node -w packages/json-csv-core
    - run: npm run build
    - name: Use Node.js ${{ matrix.node-version }} for test runtime
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd test-runner-core && npm i --omit=dev && npm test
