name: Publish @iwsio/json-csv-core to npmjs.com
on:
  workflow_call:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm config set tag-version-prefix 'json-csv-core v'
          git fetch
          git pull origin main
          npm version patch -w packages/json-csv-core -m "@iwsio/json-csv-core %s publish."
          git push
          git push --tags
      - run: npm ci -w packages/json-csv-node -w packages/json-csv-core
      - run: npm run build
      - run: npm publish --access public -w packages/json-csv-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}