# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test @iwsio/json-csv-node

on:
  workflow_call:

jobs:
  test-legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js 24 (for build)
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'
    - run: npm ci -w packages/json-csv-node -w packages/json-csv-core
    - run: npm run build
    - name: Use Node.js ${{ matrix.node-version }} for test runtime
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd test-runner && npm i --omit=dev && npm test test/*.cjs # note: only CJS files
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 22.x, 24.x]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js 24 (for build)
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'
    - run: npm ci -w packages/json-csv-node -w packages/json-csv-core
    - run: npm run build
    - name: Use Node.js ${{ matrix.node-version }} for test runtime
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd test-runner && npm i --omit=dev && npm test
