name: Publish @iwsio/json-csv-node to npmjs.com
on:
  workflow_call:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch && git pull origin ${{ github.ref_name }}
          npm version patch -w packages/json-csv-node && git add .
          VER=`node ./npm-version-helper.cjs packages/json-csv-node`
          git commit -m "@iwsio/json-csv-node version bump to $VER"
          git tag -am "@iwsio/json-csv-node $VER publish." "json-csv-node-$VER"
          git push
          git push --tags
      - run: npm run build
      - run: npm publish --access public -w packages/json-csv-node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}