name: "PR to main - @iwsio/json-csv-core"

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/json-csv-core/**'
jobs:
  test:
    if: ${{github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/core-test.yaml
