name: PR to json-csv (legacy)

on:
  pull_request:
    branches: [ json-csv ]

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/legacy-test.yml
