name: Push to main - @iwsio/json-csv-node

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/json-csv-node/**'

jobs:
  test:
    uses: ./.github/workflows/node-test.yaml
  version-and-publish:
    needs: test
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: ./.github/workflows/node-publish.yaml
    secrets: inherit
